package vault

var cfsslCMTemplate = `apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Name }}-server-cfssl
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: {{ index .Labels "app.kubernetes.io/name" }}
    app.kubernetes.io/instance: {{ index .Labels "app.kubernetes.io/instance" }}
data:
  secret_name: {{ .Name }}-server-tls
  config.json: |-
    {
      "signing": {
        "default": {
          "expiry": "168h"
        },
        "profiles": {
            "server": {
              "expiry": "8760h",
              "usages": [
                "signing",
                "key encipherment",
                "server auth"
              ]
            }
        }
      },
      "key": {
        "algo": "rsa",
        "size": 2048
      }
    }
  ca_csr.json: |-
    {
      "CN": "Autogenerated CA",
      "key": {
        "algo": "rsa",
        "size": 2048
      },
      "names": [
        {
          "C": "US",
          "ST": "CA",
          "L": "San Francisco",
          "O": "Autogen CA for Vault"
        }
      ]
    }
  0_server_csr.json: |-
    {
      "CN": "vault-server",
      "hosts": [
        "::1",
        "127.0.0.1",
        "localhost",
        "{{ .Name }}-server.{{ .Namespace }}.svc"
      ],
      "key": {
        "algo": "rsa",
        "size": 2048
      },
      "names": [
        {
          "C": "US",
          "ST": "CA",
          "L": "San Francisco"
        }
      ]
    }
  1_server_csr.json: |-
    {
      "CN": "vault-server",
      "hosts": [
        "::1",
        "127.0.0.1",
        "localhost",
        "{{ .Name }}-server.{{ .Namespace }}.svc"
      ],
      "key": {
        "algo": "rsa",
        "size": 2048
      },
      "names": [
        {
          "C": "US",
          "ST": "CA",
          "L": "San Francisco"
        }
      ]
    }
  2_server_csr.json: |-
    {
      "CN": "vault-server",
      "hosts": [
        "::1",
        "127.0.0.1",
        "localhost",
        "{{ .Name }}-server.{{ .Namespace }}.svc"
      ],
      "key": {
        "algo": "rsa",
        "size": 2048
      },
      "names": [
        {
          "C": "US",
          "ST": "CA",
          "L": "San Francisco"
        }
      ]
    }
`
